INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(1, 'Áo thun nam Active Dry cổ tròn', 'Áo thun nam chất liệu polyester co giãn 4 chiều, bề mặt vải thoáng khí, phù hợp tập luyện nhẹ và mặc hằng ngày. Form regular tôn dáng, dễ phối với jeans hoặc jogger. Đường may vai và nách gia cố để giữ form sau nhiều lần giặt máy. Tu khoa tim kiem: ao thun nam, the thao, thoang khi, dry fit, mac hang ngay.', 1, 1, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 429000.00, 4.6, 184);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(2, 'Quần jeans nam straight fit xanh đậm', 'Quần jeans nam form straight fit, chất denim pha spandex tạo cảm giác thoải mái khi ngồi lâu hoặc di chuyển nhiều. Cạp chắc, đường may đũng gia cố, phù hợp đi làm và đi chơi cuối tuần. Màu xanh đậm dễ phối áo sơ mi, áo thun và áo khoác. Tu khoa tim kiem: quan jeans nam, straight fit, denim, di lam, pho do.', 14, 3, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 899000.00, 4.5, 132);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(3, 'Giày thể thao nam RunFlex đế êm', 'Giày thể thao nam thiết kế ôm chân vừa phải, đế cao su bám sàn tốt trên bề mặt đô thị. Lót trong êm và thoáng khí, phù hợp đi bộ đường dài, tập nhẹ và sử dụng hằng ngày. Form hiện đại, phối tốt với quần jogger hoặc jeans. Tu khoa tim kiem: giay the thao nam, de em, di bo, runflex, sneaker.', 2, 5, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1299000.00, 4.7, 221);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(4, 'Áo khoác nữ gió nhẹ Urban Shell', 'Áo khoác nữ chất liệu nhẹ, cản gió cơ bản, phù hợp di chuyển buổi sáng và chiều tối. Form vừa vặn, dễ phối với váy hoặc quần jeans. Bề mặt ít nhăn và nhanh khô, tiện cho lịch trình bận rộn. Tu khoa tim kiem: ao khoac nu, can gio, di lam, urban, thoi trang nu.', 16, 12, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1199000.00, 4.4, 96);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(5, 'Váy nữ midi Linen Grace', 'Váy midi nữ chất liệu linen pha, bề mặt mềm và thoáng, phù hợp mặc cả ngày trong môi trường văn phòng hoặc dạo phố. Thiết kế tối giản, tôn dáng, dễ phối cùng blazer hoặc cardigan mỏng. Tu khoa tim kiem: vay midi, linen, nu tinh, di lam, smart casual.', 15, 10, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 759000.00, 4.5, 113);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(6, 'Giày nữ Classic Heel 5cm', 'Giày nữ gót thấp 5cm, thiết kế thanh lịch cho môi trường công sở và sự kiện nhẹ. Phần lót mềm, giảm áp lực mũi chân khi di chuyển. Dáng giày dễ phối với chân váy, quần tây hoặc jeans ôm. Tu khoa tim kiem: giay nu, got thap, cong so, thanh lich, classic.', 13, 11, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1099000.00, 4.3, 78);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(7, 'Áo trẻ em cotton mềm SoftPlay', 'Áo trẻ em cotton mềm, thân thiện da nhạy cảm, thoáng và thấm hút tốt. Form vừa vặn, dễ cử động khi vui chơi và đi học. Họa tiết đơn giản, màu sắc tươi sáng phù hợp lứa tuổi từ 6 đến 12. Tu khoa tim kiem: ao tre em, cotton mem, an toan da, di hoc, be trai be gai.', 11, 13, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 239000.00, 4.7, 165);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(8, 'Balo học sinh SmartPack 20L', 'Balo học sinh dung tích 20L, ngăn chính rộng và ngăn phụ khoa học. Quai đeo có đệm êm, phân bổ lực tốt cho vai, phù hợp học sinh cấp 2 và cấp 3. Chất liệu bền nhẹ, chống bám bụi cơ bản và dễ vệ sinh. Tu khoa tim kiem: balo hoc sinh, 20l, ngan chong soc, quai dem em, di hoc.', 10, 16, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 529000.00, 4.6, 142);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(9, 'Mũ lưỡi trai unisex AirCap', 'Mũ lưỡi trai unisex form đứng, chất liệu nhẹ và thoáng, phù hợp hoạt động ngoài trời và đi lại hằng ngày. Phần khóa điều chỉnh linh hoạt, ôm đầu ổn định cho nhiều vòng đầu khác nhau. Tu khoa tim kiem: mu luoi trai, unisex, ngoai troi, streetwear, phu kien.', 17, 17, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 329000.00, 4.4, 87);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(10, 'Túi đeo chéo urban mini', 'Túi đeo chéo mini phong cách đường phố, tối ưu cho vật dụng thiết yếu như điện thoại, ví và tai nghe. Thiết kế gọn, dây đeo điều chỉnh nhanh, chất liệu bền chống bám bụi nhẹ. Phù hợp đi chơi, dạo phố và du lịch ngắn ngày. Tu khoa tim kiem: tui deo cheo, urban, mini bag, streetwear, phu kien.', 18, 18, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 459000.00, 4.5, 64);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(11, 'Áo thun nam Nike Core 1', 'Áo thun nam dòng Core của Nike, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo thun nam, nike, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo thun nam, nike, core, de pho do, mac hang ngay.', 1, 1, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 429000.00, 4.0, 40);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(12, 'Áo khoác nam Adidas Core 2', 'Áo khoác nam dòng Core của Adidas, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo khoác nam, adidas, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo khoác nam, adidas, core, de pho do, mac hang ngay.', 2, 6, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 476000.00, 4.1, 49);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(13, 'Giày nữ Puma Core 3', 'Giày nữ dòng Core của Puma, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: giày nữ, puma, core, mac hang ngay, de pho do. Tu khoa tim kiem: giày nữ, puma, core, de pho do, mac hang ngay.', 3, 11, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1084000.00, 4.2, 58);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(14, 'Phụ kiện thời trang Puma Core 4', 'Phụ kiện thời trang dòng Core của Puma, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: phụ kiện thời trang, puma, core, mac hang ngay, de pho do. Tu khoa tim kiem: phụ kiện thời trang, puma, core, de pho do, mac hang ngay.', 3, 18, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 500000.00, 4.3, 67);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(15, 'Balo học sinh Converse Core 5', 'Balo học sinh dòng Core của Converse, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: balo học sinh, converse, core, mac hang ngay, de pho do. Tu khoa tim kiem: balo học sinh, converse, core, de pho do, mac hang ngay.', 4, 16, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 547000.00, 4.4, 76);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(16, 'Giày thể thao nam Converse Core 6', 'Giày thể thao nam dòng Core của Converse, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: giày thể thao nam, converse, core, mac hang ngay, de pho do. Tu khoa tim kiem: giày thể thao nam, converse, core, de pho do, mac hang ngay.', 4, 5, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1225000.00, 4.5, 85);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(33, 'Mũ nón H&M Core 23', 'Mũ nón dòng Core của H&M, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: mũ nón, h&m, core, mac hang ngay, de pho do. Tu khoa tim kiem: mũ nón, h&m, core, de pho do, mac hang ngay.', 15, 17, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 553000.00, 4.6, 238);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(17, 'Quần jeans nam Vans Core 7', 'Quần jeans nam dòng Core của Vans, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần jeans nam, vans, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần jeans nam, vans, core, de pho do, mac hang ngay.', 5, 3, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 431000.00, 4.6, 94);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(18, 'Váy nữ Vans Core 8', 'Váy nữ dòng Core của Vans, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: váy nữ, vans, core, mac hang ngay, de pho do. Tu khoa tim kiem: váy nữ, vans, core, de pho do, mac hang ngay.', 5, 10, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 678000.00, 4.7, 103);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(19, 'Áo sơ mi nữ Ananas Core 9', 'Áo sơ mi nữ dòng Core của Ananas, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo sơ mi nữ, ananas, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo sơ mi nữ, ananas, core, de pho do, mac hang ngay.', 6, 8, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 525000.00, 4.0, 112);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(20, 'Giày trẻ em Ananas Core 10', 'Giày trẻ em dòng Core của Ananas, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: giày trẻ em, ananas, core, mac hang ngay, de pho do. Tu khoa tim kiem: giày trẻ em, ananas, core, de pho do, mac hang ngay.', 6, 15, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1133000.00, 4.1, 121);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(21, 'Áo trẻ em Biti''s Hunter Core 11', 'Áo trẻ em dòng Core của Biti''s Hunter, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo trẻ em, biti''s hunter, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo trẻ em, biti''s hunter, core, de pho do, mac hang ngay.', 7, 13, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 429000.00, 4.2, 130);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(22, 'Áo sơ mi nam Biti''s Hunter Core 12', 'Áo sơ mi nam dòng Core của Biti''s Hunter, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo sơ mi nam, biti''s hunter, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo sơ mi nam, biti''s hunter, core, de pho do, mac hang ngay.', 7, 2, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 666000.00, 4.3, 139);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(23, 'Áo thun nam Coolmate Core 13', 'Áo thun nam dòng Core của Coolmate, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo thun nam, coolmate, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo thun nam, coolmate, core, de pho do, mac hang ngay.', 8, 1, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 433000.00, 4.4, 148);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(24, 'Áo thun nữ Coolmate Core 14', 'Áo thun nữ dòng Core của Coolmate, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo thun nữ, coolmate, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo thun nữ, coolmate, core, de pho do, mac hang ngay.', 8, 7, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 480000.00, 4.5, 157);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(25, 'Giày thể thao nam Routine Core 15', 'Giày thể thao nam dòng Core của Routine, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: giày thể thao nam, routine, core, mac hang ngay, de pho do. Tu khoa tim kiem: giày thể thao nam, routine, core, de pho do, mac hang ngay.', 9, 5, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1088000.00, 4.6, 166);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(26, 'Áo khoác nữ Routine Core 16', 'Áo khoác nữ dòng Core của Routine, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo khoác nữ, routine, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo khoác nữ, routine, core, de pho do, mac hang ngay.', 9, 12, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 574000.00, 4.7, 175);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(27, 'Váy nữ Yody Core 17', 'Váy nữ dòng Core của Yody, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: váy nữ, yody, core, mac hang ngay, de pho do. Tu khoa tim kiem: váy nữ, yody, core, de pho do, mac hang ngay.', 10, 10, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 821000.00, 4.0, 184);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(28, 'Giày trẻ em Canifa Core 18', 'Giày trẻ em dòng Core của Canifa, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: giày trẻ em, canifa, core, mac hang ngay, de pho do. Tu khoa tim kiem: giày trẻ em, canifa, core, de pho do, mac hang ngay.', 11, 15, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 1229000.00, 4.1, 193);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(29, 'Áo sơ mi nam Lining Core 19', 'Áo sơ mi nam dòng Core của Lining, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo sơ mi nam, lining, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo sơ mi nam, lining, core, de pho do, mac hang ngay.', 12, 2, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 435000.00, 4.2, 202);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(30, 'Quần jeans nữ Lining Core 20', 'Quần jeans nữ dòng Core của Lining, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần jeans nữ, lining, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần jeans nữ, lining, core, de pho do, mac hang ngay.', 12, 9, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 482000.00, 4.3, 211);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(31, 'Áo thun nữ MLB Core 21', 'Áo thun nữ dòng Core của MLB, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo thun nữ, mlb, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo thun nữ, mlb, core, de pho do, mac hang ngay.', 13, 7, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 529000.00, 4.4, 220);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(32, 'Quần trẻ em Uniqlo Core 22', 'Quần trẻ em dòng Core của Uniqlo, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần trẻ em, uniqlo, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần trẻ em, uniqlo, core, de pho do, mac hang ngay.', 14, 14, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 386000.00, 4.5, 229);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(34, 'Quần jogger nam Zara Core 24', 'Quần jogger nam dòng Core của Zara, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần jogger nam, zara, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần jogger nam, zara, core, de pho do, mac hang ngay.', 16, 4, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 670000.00, 4.7, 247);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(35, 'Quần jeans nữ DirtyCoins Core 25', 'Quần jeans nữ dòng Core của DirtyCoins, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần jeans nữ, dirtycoins, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần jeans nữ, dirtycoins, core, de pho do, mac hang ngay.', 17, 9, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 437000.00, 4.0, 256);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(36, 'Quần trẻ em 5THEWAY Core 26', 'Quần trẻ em dòng Core của 5THEWAY, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần trẻ em, 5theway, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần trẻ em, 5theway, core, de pho do, mac hang ngay.', 18, 14, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 294000.00, 4.1, 265);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(37, 'Quần jeans nam Davies Core 27', 'Quần jeans nam dòng Core của Davies, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần jeans nam, davies, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần jeans nam, davies, core, de pho do, mac hang ngay.', 19, 3, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 531000.00, 4.2, 274);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(38, 'Áo sơ mi nữ Davies Core 28', 'Áo sơ mi nữ dòng Core của Davies, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo sơ mi nữ, davies, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo sơ mi nữ, davies, core, de pho do, mac hang ngay.', 19, 8, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 578000.00, 4.3, 283);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(39, 'Áo khoác nam Degrey Core 29', 'Áo khoác nam dòng Core của Degrey, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: áo khoác nam, degrey, core, mac hang ngay, de pho do. Tu khoa tim kiem: áo khoác nam, degrey, core, de pho do, mac hang ngay.', 20, 6, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 625000.00, 4.4, 292);
INSERT INTO public.products
(id, "name", description, brand_id, category_id, is_active, created_at, updated_at, price, average_rating, review_count)
VALUES(40, 'Quần jogger nam Degrey Core 30', 'Quần jogger nam dòng Core của Degrey, tối ưu cho nhu cầu mặc hằng ngày và di chuyển linh hoạt. Chất liệu chọn lọc, hoàn thiện chắc chắn, dễ phối theo nhiều phong cách từ basic đến streetwear. Tu khoa tim kiem: quần jogger nam, degrey, core, mac hang ngay, de pho do. Tu khoa tim kiem: quần jogger nam, degrey, core, de pho do, mac hang ngay.', 20, 4, true, '2026-03-26 14:52:35.367', '2026-03-26 14:52:35.367', 672000.00, 4.5, 301);