import 'reflect-metadata';
import { join } from 'node:path';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import {
  User,
  UserFollow,
  Address,
  Wishlist,
  Cart,
  CartItem,
  Brand,
  Category,
  Color,
  SizeType,
  Size,
  Product,
  ProductImage,
  ProductVariant,
  ProductTryonAsset,
  Inventory,
  InventoryTransaction,
  Order,
  OrderItem,
  Coupon,
  CouponRedemption,
  Review,
  ReviewImage,
  ReviewVote,
  Post,
  PostComment,
  PostImage,
  PostLike,
  Hashtag,
  PostHashtag,
  Notification,
  DeviceToken,
  UserInteraction,
  Conversation,
  Message,
  AiChatSession,
  AiChatMessage,
  Livestream,
  LivestreamComment,
  LivestreamProduct,
  LivestreamOrder,
  Payment,
  PaymentRetry,
  Shipment,
  Outfit,
  OutfitItem,
  SlotType,
  SystemSetting,
} from './entities';

/**
 * TypeORM CLI DataSource configuration
 * Used for migration commands and database operations outside of NestJS app context
 */
dotenv.config();

const migrationExtension = __filename.endsWith('.ts') ? 'ts' : 'js';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DATABASE_HOST || 'localhost',
  port: parseInt(process.env.DATABASE_PORT ?? '5432', 10),
  username: process.env.DATABASE_USER || 'username',
  password: process.env.DATABASE_PASSWORD || '123456',
  database: process.env.DATABASE_NAME || 'fshop_db',
  ssl:
    process.env.DB_USE_SSL === 'true' ? { rejectUnauthorized: false } : false,
  entities: [
    User,
    UserFollow,
    Address,
    Wishlist,
    Cart,
    CartItem,
    Brand,
    Category,
    Color,
    SizeType,
    Size,
    Product,
    ProductImage,
    ProductVariant,
    ProductTryonAsset,
    Inventory,
    InventoryTransaction,
    Order,
    OrderItem,
    Coupon,
    CouponRedemption,
    Review,
    ReviewImage,
    ReviewVote,
    Post,
    PostComment,
    PostImage,
    PostLike,
    Hashtag,
    PostHashtag,
    Notification,
    DeviceToken,
    UserInteraction,
    Conversation,
    Message,
    AiChatSession,
    AiChatMessage,
    Livestream,
    LivestreamComment,
    LivestreamProduct,
    LivestreamOrder,
    Payment,
    PaymentRetry,
    Shipment,
    Outfit,
    OutfitItem,
    SlotType,
    SystemSetting,
  ],
  migrations: [join(__dirname, 'migrations', `*.${migrationExtension}`)],
  synchronize: false,
  // Enable ssl when using managed DBs (Neon, etc.)
});
