import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import {
  User,
  Address,
  Wishlist,
  Cart,
  CartItem,
  Brand,
  Category,
  Color,
  SizeType,
  Size,
  Product,
  ProductImage,
  ProductVariant,
  ProductTryonAsset,
  Inventory,
  InventoryTransaction,
  Order,
  OrderItem,
  Coupon,
  CouponRedemption,
  Review,
  ReviewImage,
  ReviewVote,
  Post,
  PostComment,
  PostImage,
  PostLike,
  Hashtag,
  PostHashtag,
  Notification,
  DeviceToken,
  UserInteraction,
  Conversation,
  Message,
  AiChatSession,
  AiChatMessage,
  Livestream,
  LivestreamComment,
  LivestreamProduct,
  LivestreamOrder,
  Payment,
  PaymentRetry,
} from './entities';

/**
 * TypeORM CLI DataSource configuration
 * Used for migration commands and database operations outside of NestJS app context
 */
dotenv.config();

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT as string, 10),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [
    User,
    Address,
    Wishlist,
    Cart,
    CartItem,
    Brand,
    Category,
    Color,
    SizeType,
    Size,
    Product,
    ProductImage,
    ProductVariant,
    ProductTryonAsset,
    Inventory,
    InventoryTransaction,
    Order,
    OrderItem,
    Coupon,
    CouponRedemption,
    Review,
    ReviewImage,
    ReviewVote,
    Post,
    PostComment,
    PostImage,
    PostLike,
    Hashtag,
    PostHashtag,
    Notification,
    DeviceToken,
    UserInteraction,
    Conversation,
    Message,
    AiChatSession,
    AiChatMessage,
    Livestream,
    LivestreamComment,
    LivestreamProduct,
    LivestreamOrder,
    Payment,
    PaymentRetry,
  ],
  migrations: ['src/migrations/*.ts'],
  synchronize: false,
  // Enable ssl when using managed DBs (Neon, etc.)
  ssl: process.env.DB_USE_SSL === 'true' ? { rejectUnauthorized: false } : undefined,
});
